spring:
  application:
    name: starter
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      client-name: JEDIS
      timeout: 3000
      username: ${REDIS_USERNAME}
  ai:
    openai:
      temperature: 0.3
      api-key: ${AI_API_KEY}
      model: gpt-4o
    vectorstore:
      redis:
        index: faqs
        prefix: "faq:"
        initialize-schema: true
    embedding:
      transformer:
        onnx:
          modelUri: https://huggingface.co/intfloat/e5-small-v2/resolve/main/model.onnx
      tokenizer:
        uri: https://huggingface.co/intfloat/e5-small-v2/raw/main/tokenizer.json